"""Add DataState enum to CompetitorSource

Revision ID: 2c219025a773
Revises: 41a34b11d31d
Create Date: 2026-08-14 20:19:51.168081
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c219025a773'
down_revision: str | None = '41a34b11d31d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql
    datastate_enum = postgresql.ENUM('VALID', 'STALE', 'NO_DATA', 'EXTRACTION_FAILED', name='competitor_source_data_state_enum')
    datastate_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_state', sa.Enum('VALID', 'STALE', 'NO_DATA', 'EXTRACTION_FAILED', name='competitor_source_data_state_enum', create_constraint=True), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor_sources', schema=None) as batch_op:
        batch_op.drop_column('data_state')

    # ### end Alembic commands ###
