"""Add missing tables

Revision ID: 41a34b11d31d
Revises: d4e5f6a7b8c9
Create Date: 2026-08-14 15:52:29.998876
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41a34b11d31d'
down_revision: str | None = 'd4e5f6a7b8c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('roi_estimate', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('affected_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Detected business opportunities'
    )
    with op.batch_alter_table('business_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_opportunities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_opportunities_opportunity_type'), ['opportunity_type'], unique=False)

    op.create_table('forecast_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benchmark_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regional_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Generated forecast reports'
    )
    with op.batch_alter_table('forecast_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_reports_id'), ['id'], unique=False)

    op.create_table('market_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('INCREASING', 'DECREASING', 'STABLE', 'EMERGING', name='trend_direction_enum', create_constraint=True), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Detected market trends'
    )
    with op.batch_alter_table('market_trends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_trends_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trends_id'), ['id'], unique=False)
        batch_op.create_index('ix_trend_category_direction', ['category', 'direction'], unique=False)

    op.create_table('strategic_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('expected_benefit', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='recommendation_risk_level_enum', create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Strategic recommendations'
    )
    with op.batch_alter_table('strategic_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategic_recommendations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategic_recommendations_id'), ['id'], unique=False)

    op.create_table('competitor_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.Enum('GROWTH', 'PRICING', 'SERVICE_LAUNCH', 'MARKET_MOVEMENT', 'EXPANSION', name='prediction_type_enum', create_constraint=True), nullable=False),
    sa.Column('prediction_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Predictive intelligence per competitor'
    )
    with op.batch_alter_table('competitor_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_predictions_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_predictions_prediction_type'), ['prediction_type'], unique=False)
        batch_op.create_index('ix_prediction_competitor_type', ['competitor_id', 'prediction_type'], unique=False)

    op.create_table('competitor_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum', create_constraint=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('likelihood', sa.Float(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Competitor risk analysis'
    )
    with op.batch_alter_table('competitor_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_risks_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_risks_id'), ['id'], unique=False)
        batch_op.create_index('ix_risk_competitor_type', ['competitor_id', 'risk_type'], unique=False)

    op.create_table('predictive_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('current_rank', sa.Integer(), nullable=False),
    sa.Column('predicted_rank', sa.Integer(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('innovation_score', sa.Float(), nullable=False),
    sa.Column('expansion_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('overall_prediction', sa.String(length=20), nullable=False),
    sa.Column('benchmark_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', name='uq_benchmark_competitor'),
    comment='Predictive benchmarking data'
    )
    with op.batch_alter_table('predictive_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictive_benchmarks_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictive_benchmarks_id'), ['id'], unique=False)

    op.create_table('regional_expansions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('expansion_probability', sa.Float(), nullable=False),
    sa.Column('expansion_score', sa.Float(), nullable=False),
    sa.Column('expected_timeline', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Regional expansion forecasts'
    )
    with op.batch_alter_table('regional_expansions', schema=None) as batch_op:
        batch_op.create_index('ix_expansion_competitor_region', ['competitor_id', 'region'], unique=False)
        batch_op.create_index(batch_op.f('ix_regional_expansions_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regional_expansions_id'), ['id'], unique=False)

    with op.batch_alter_table('ai_insight_feedback', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('collection_logs', schema=None) as batch_op:
        batch_op.create_index('ix_collection_log_success', ['success'], unique=False)

    with op.batch_alter_table('competitor_ai_insights', schema=None) as batch_op:
        batch_op.create_index('ix_ai_insight_llm_provider', ['llm_provider'], unique=False)
        batch_op.create_index('ix_ai_insight_prompt_version', ['prompt_version'], unique=False)

    with op.batch_alter_table('competitor_change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_change_events_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_change_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_change_events_event_type'), ['event_type'], unique=False)
        batch_op.create_table_comment(
        'Tracks granular change deltas for predictive analysis',
        existing_comment=None
    )

    with op.batch_alter_table('prediction_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_evaluations_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_table_comment(
        'Historical backtesting and actual vs. forecast validation',
        existing_comment=None
    )

    with op.batch_alter_table('raw_storage', schema=None) as batch_op:
        batch_op.create_index('ix_raw_storage_extracted_data_gin', ['extracted_data'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_storage', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_storage_extracted_data_gin', postgresql_using='gin')

    with op.batch_alter_table('prediction_evaluations', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Historical backtesting and actual vs. forecast validation'
    )
        batch_op.drop_index(batch_op.f('ix_prediction_evaluations_competitor_id'))

    with op.batch_alter_table('competitor_change_events', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Tracks granular change deltas for predictive analysis'
    )
        batch_op.drop_index(batch_op.f('ix_competitor_change_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_competitor_change_events_detected_at'))
        batch_op.drop_index(batch_op.f('ix_competitor_change_events_competitor_id'))

    with op.batch_alter_table('competitor_ai_insights', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_insight_prompt_version')
        batch_op.drop_index('ix_ai_insight_llm_provider')

    with op.batch_alter_table('collection_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_log_success')

    with op.batch_alter_table('ai_insight_feedback', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('regional_expansions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regional_expansions_id'))
        batch_op.drop_index(batch_op.f('ix_regional_expansions_competitor_id'))
        batch_op.drop_index('ix_expansion_competitor_region')

    op.drop_table('regional_expansions')
    with op.batch_alter_table('predictive_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictive_benchmarks_id'))
        batch_op.drop_index(batch_op.f('ix_predictive_benchmarks_competitor_id'))

    op.drop_table('predictive_benchmarks')
    with op.batch_alter_table('competitor_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_competitor_type')
        batch_op.drop_index(batch_op.f('ix_competitor_risks_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_risks_competitor_id'))

    op.drop_table('competitor_risks')
    with op.batch_alter_table('competitor_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_prediction_competitor_type')
        batch_op.drop_index(batch_op.f('ix_competitor_predictions_prediction_type'))
        batch_op.drop_index(batch_op.f('ix_competitor_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_predictions_competitor_id'))

    op.drop_table('competitor_predictions')
    with op.batch_alter_table('strategic_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategic_recommendations_id'))
        batch_op.drop_index(batch_op.f('ix_strategic_recommendations_category'))

    op.drop_table('strategic_recommendations')
    with op.batch_alter_table('market_trends', schema=None) as batch_op:
        batch_op.drop_index('ix_trend_category_direction')
        batch_op.drop_index(batch_op.f('ix_market_trends_id'))
        batch_op.drop_index(batch_op.f('ix_market_trends_category'))

    op.drop_table('market_trends')
    with op.batch_alter_table('forecast_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_reports_id'))

    op.drop_table('forecast_reports')
    with op.batch_alter_table('business_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_opportunities_opportunity_type'))
        batch_op.drop_index(batch_op.f('ix_business_opportunities_id'))

    op.drop_table('business_opportunities')
    # ### end Alembic commands ###
