"""Add extracted_data to raw_storage and competitor_pages

Revision ID: 6e50441e8997
Revises: a1b2c3d4e5f6
Create Date: 2026-07-07 20:39:17.176659
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e50441e8997'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_pages', sa.Column('extracted_data', sa.JSON(), nullable=True))
    op.add_column('raw_storage', sa.Column('extracted_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_storage', 'extracted_data')
    op.drop_column('competitor_pages', 'extracted_data')
    # ### end Alembic commands ###
