"""Initial PostgreSQL schema

Revision ID: 712fdbe261ba
Revises:
Create Date: 2026-07-23 10:05:16.749509
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '712fdbe261ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('collection_frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', name='collection_frequency_enum', create_constraint=True), nullable=False),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Registered competitor websites'
    )
    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks changes between collections'
    )
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.create_index('ix_change_log_competitor_id', ['competitor_id'], unique=False)
        batch_op.create_index('ix_change_log_data_type', ['data_type'], unique=False)
        batch_op.create_index('ix_change_log_detected_at', ['detected_at'], unique=False)

    op.create_table('collection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('records_collected', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit trail of all collection runs'
    )
    with op.batch_alter_table('collection_logs', schema=None) as batch_op:
        batch_op.create_index('ix_collection_log_competitor_id', ['competitor_id'], unique=False)
        batch_op.create_index('ix_collection_log_start_time', ['start_time'], unique=False)

    op.create_table('competitor_ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_position', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('pricing_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategic_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latest_updates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_ai_insights_competitor_id'), ['competitor_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_competitor_ai_insights_id'), ['id'], unique=False)

    op.create_table('competitor_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'url', name='uq_competitor_content_url'),
    comment='Blog posts, articles, and press releases'
    )
    with op.batch_alter_table('competitor_content', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_content_competitor_id', ['competitor_id'], unique=False)
        batch_op.create_index('ix_competitor_content_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_competitor_content_url', ['url'], unique=False)

    op.create_table('competitor_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('promotional_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('membership_pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subscription_plans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'content_hash', name='uq_competitor_pricing_hash'),
    comment='Pricing data collected from competitors'
    )
    with op.batch_alter_table('competitor_pricing', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_pricing_competitor_id', ['competitor_id'], unique=False)

    op.create_table('competitor_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('service_category', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_duration', sa.String(length=100), nullable=True),
    sa.Column('starting_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_add_ons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('membership_available', sa.Boolean(), nullable=False),
    sa.Column('offers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discounts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'content_hash', name='uq_competitor_service_hash'),
    comment='Service listings collected from competitors'
    )
    with op.batch_alter_table('competitor_services', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_service_competitor_id', ['competitor_id'], unique=False)

    op.create_table('competitor_social',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('LINKEDIN', 'FACEBOOK', 'INSTAGRAM', 'TWITTER', 'YOUTUBE', 'PINTEREST', 'THREADS', name='social_platform_enum', create_constraint=True), nullable=False),
    sa.Column('profile_url', sa.String(length=2048), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'platform', name='uq_competitor_social_platform'),
    comment='Social media profiles per competitor'
    )
    with op.batch_alter_table('competitor_social', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_social_competitor_id', ['competitor_id'], unique=False)

    op.create_table('competitor_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.String(length=100), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'url', name='uq_competitor_source_url'),
    comment='Discovered URLs per competitor'
    )
    with op.batch_alter_table('competitor_sources', schema=None) as batch_op:
        batch_op.create_index('ix_competitor_source_competitor_id', ['competitor_id'], unique=False)
        batch_op.create_index('ix_competitor_source_url', ['url'], unique=False)

    op.create_table('raw_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('collection_status', sa.Enum('SUCCESS', 'FAILED', 'PARTIAL', name='collection_status_enum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'source_url', name='uq_raw_storage_competitor_url'),
    comment='Original HTML snapshots and raw data'
    )
    with op.batch_alter_table('raw_storage', schema=None) as batch_op:
        batch_op.create_index('ix_raw_storage_competitor_id', ['competitor_id'], unique=False)
        batch_op.create_index('ix_raw_storage_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_raw_storage_source_url', ['source_url'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_storage', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_storage_source_url')
        batch_op.drop_index('ix_raw_storage_content_hash')
        batch_op.drop_index('ix_raw_storage_competitor_id')

    op.drop_table('raw_storage')
    with op.batch_alter_table('competitor_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_competitor_source_url')
        batch_op.drop_index('ix_competitor_source_competitor_id')

    op.drop_table('competitor_sources')
    with op.batch_alter_table('competitor_social', schema=None) as batch_op:
        batch_op.drop_index('ix_competitor_social_competitor_id')

    op.drop_table('competitor_social')
    with op.batch_alter_table('competitor_services', schema=None) as batch_op:
        batch_op.drop_index('ix_competitor_service_competitor_id')

    op.drop_table('competitor_services')
    with op.batch_alter_table('competitor_pricing', schema=None) as batch_op:
        batch_op.drop_index('ix_competitor_pricing_competitor_id')

    op.drop_table('competitor_pricing')
    with op.batch_alter_table('competitor_content', schema=None) as batch_op:
        batch_op.drop_index('ix_competitor_content_url')
        batch_op.drop_index('ix_competitor_content_content_hash')
        batch_op.drop_index('ix_competitor_content_competitor_id')

    op.drop_table('competitor_content')
    with op.batch_alter_table('competitor_ai_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_ai_insights_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_ai_insights_competitor_id'))

    op.drop_table('competitor_ai_insights')
    with op.batch_alter_table('collection_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_log_start_time')
        batch_op.drop_index('ix_collection_log_competitor_id')

    op.drop_table('collection_logs')
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_change_log_detected_at')
        batch_op.drop_index('ix_change_log_data_type')
        batch_op.drop_index('ix_change_log_competitor_id')

    op.drop_table('change_logs')
    op.drop_table('competitors')
    # ### end Alembic commands ###
